compose: Compose-box border is subtle in dark mode
zulip/zulip-flutter pull request #1233
Opened 2024-12-29 08:55 UTC by lakshya1goel

Updated the top border and added shadow effect to the top of the compose box to ensure it is subtle in dark mode.

For reference, see the Figma design:
https://www.figma.com/design/1JTNtYo9memgW7vV6d0ygq/Zulip-Mobile?node-id=5908-64038&t=alSmAmdRXFDwT4IT-1

Fixes: #1207

2024-12-30 16:22 UTC, chrisbobbe requested changes
Thanks! I see this is a draft, but I gave it a quick skim and I noticed a different direction I'd like to take. 🙂

Since the shadow is only meant to be applied in dark theme, I'd like to avoid asking Flutter to do any computations for it when in light mode. For that, let's add a `ComposeBoxTheme` class in lib/widgets/compose_box.dart, with just one field `boxShadow` that's null in light theme and non-null in dark theme. `ContentTheme` and `MessageListTheme` are examples of the pattern I have in mind. So, something like this:

<details>
<summary>Proposal</summary>

```dart
/// Compose-box styles that differ between light and dark theme.
///
/// These styles will animate on theme changes (with help from [lerp]).
class ComposeBoxTheme extends ThemeExtension<ComposeBoxTheme> {
  factory ComposeBoxTheme.light(BuildContext context) {
    return ComposeBoxTheme._(
      boxShadow: null,
    );
  }

  factory ComposeBoxTheme.dark(BuildContext context) {
    return ComposeBoxTheme._(
      boxShadow: [BoxShadow(
        color: DesignVariables.dark.bgTopBar,
        offset: const Offset(0, -4),
        blurRadius: 16,
        spreadRadius: 0,
      )],
    );
  }

  ComposeBoxTheme._({
    required this.boxShadow,
  });

  /// The [ComposeBoxTheme] from the context's active theme.
  ///
  /// The [ThemeData] must include [ComposeBoxTheme] in [ThemeData.extensions].
  static ComposeBoxTheme of(BuildContext context) {
    final theme = Theme.of(context);
    final extension = theme.extension<ComposeBoxTheme>();
    assert(extension != null);
    return extension!;
  }

  final List<BoxShadow>? boxShadow;

  @override
  ComposeBoxTheme copyWith({
    List<BoxShadow>? boxShadow,
  }) {
    return ComposeBoxTheme._(
      boxShadow: boxShadow ?? this.boxShadow,
    );
  }

  @override
  ComposeBoxTheme lerp(ComposeBoxTheme other, double t) {
    if (identical(this, other)) {
      return this;
    }
    return ComposeBoxTheme._(
      boxShadow: BoxShadow.lerpList(boxShadow, other.boxShadow, t)!,
    );
  }
}
```

</details>

Then the caller can say `boxShadow: ComposeBoxTheme.of(context).boxShadow`.

Note the use of `DesignVariables.dark.bgTopBar` instead of adding a new design variable. The Figma doesn't add any new design variables. Also, it's `DesignVariables.dark.bgTopBar` instead of `DesignVariables.dark().bgTopBar` because of a small optimization, #1236; I suggest rebasing your work atop that PR to get that optimization.

2024-12-30 16:22 UTC, chrisbobbe commented on lib/widgets/theme.dart
> +      composeBoxBorderBar: Colors.white.withValues(alpha: 0.1),
The Figma doesn't add a new design variable for the compose box border bar, it just changes the dark-theme value of an existing variable, `border-bar`. We should do the same.

2024-12-30 16:22 UTC, chrisbobbe commented on lib/widgets/theme.dart
> +      composeBoxShadow: const Color(0xff242424),
The Figma uses an existing variable for the shadow color, `bg-top-bar`; we should do the same.

2025-01-04 06:23 UTC, lakshya1goel commented
Thanks for the review, I am working on it and will update it as required ASAP.
Thanks!

2025-01-15 20:09 UTC, PIG208 commented
There is a merge conflict. Could you resolve it? Thanks!

2025-01-17 13:50 UTC, 0pni approved these changes
🥳

2025-01-18 03:55 UTC, lakshya1goel commented
Pushed the changes atop https://github.com/zulip/zulip-flutter/pull/1290 for the sake of CI.

2025-01-22 00:14 UTC, chrisbobbe commented on lib/widgets/compose_box.dart
> +  }
Ah a small improvement on my proposal above 🙂 these don't actually need a `BuildContext` so they can just be static final fields:

```dart
  static final light = ComposeBoxTheme._(
    boxShadow: null,
  );

  static final dark = ComposeBoxTheme._(
    boxShadow: [BoxShadow(
      color: DesignVariables.dark.bgTopBar,
      offset: const Offset(0, -4),
      blurRadius: 16,
      spreadRadius: 0,
    )],
  );
```

2025-01-22 04:58 UTC, 0pni approved these changes

2025-01-22 04:59 UTC, lakshya1goel commented
Hello, @chrisbobbe thanks for mentioning the changes. I have updated it accordingly. 
Please have a look and let me know if anything else is required.
Thanks!

2025-01-22 20:54 UTC, PIG208 reviewed
This looks good to me! Left some comments, where only the commit message nit is actionable right now.

2025-01-22 20:54 UTC, PIG208 commented on lib/widgets/compose_box.dart
>  import 'text.dart';
commit message nit:

```
compose: Compose-box border is subtle in dark mode 
```

Let's [start the commit summary line with an imperative verb](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.html#commit-summary-part-2) instead.

2025-01-22 20:54 UTC, PIG208 commented on lib/widgets/compose_box.dart
> +      boxShadow: boxShadow ?? this.boxShadow,
This is quite a nit and not a blocker for this PR: there is no way for a caller of `copyWith` to override the value of `boxShadow` to `null`, which is a valid value.

`ThemeExtension` documents the method this way:

```
  /// Creates a copy of this theme extension with the given fields
  /// replaced by the non-null parameter values.
  ThemeExtension<T> copyWith();
```

I guess using nullable values for theme extension fields is uncommon but not incorrect. But there can be instances where the distinction between absent/null arguments matter.

2025-01-22 20:54 UTC, PIG208 commented on lib/widgets/compose_box.dart
> +      boxShadow: BoxShadow.lerpList(boxShadow, other.boxShadow, t)!,
I wonder how `lerpList` works if one of the `BoxShadow` is `null`, and what happens when the animation happens.

<details>
<summary>Implementation</summary>

```
  /// Linearly interpolate between two box shadows.
  ///
  /// If either box shadow is null, this function linearly interpolates from
  /// a box shadow that matches the other box shadow in color but has a zero
  /// offset and a zero blurRadius.
  ///
  /// {@macro dart.ui.shadow.lerp}
  static BoxShadow? lerp(BoxShadow? a, BoxShadow? b, double t) {
    if (identical(a, b)) {
      return a;
    }
    if (a == null) {
      return b!.scale(t);
    }
    if (b == null) {
      return a.scale(1.0 - t);
    }
    return BoxShadow(
      color: Color.lerp(a.color, b.color, t)!,
      offset: Offset.lerp(a.offset, b.offset, t)!,
      blurRadius: ui.lerpDouble(a.blurRadius, b.blurRadius, t)!,
      spreadRadius: ui.lerpDouble(a.spreadRadius, b.spreadRadius, t)!,
      blurStyle: a.blurStyle == BlurStyle.normal ? b.blurStyle : a.blurStyle,
    );
  }

  /// Linearly interpolate between two lists of box shadows.
  ///
  /// If the lists differ in length, excess items are lerped with null.
  ///
  /// {@macro dart.ui.shadow.lerp}
  static List<BoxShadow>? lerpList(List<BoxShadow>? a, List<BoxShadow>? b, double t) {
    if (identical(a, b)) {
      return a;
    }
    a ??= <BoxShadow>[];
    b ??= <BoxShadow>[];
    final int commonLength = math.min(a.length, b.length);
    return <BoxShadow>[
      for (int i = 0; i < commonLength; i += 1) BoxShadow.lerp(a[i], b[i], t)!,
      for (int i = commonLength; i < a.length; i += 1) a[i].scale(1.0 - t),
      for (int i = commonLength; i < b.length; i += 1) b[i].scale(t),
    ];
  }
```

</details>

So effectively, the `lerpList` only applies to the non-null `BoxShadow`, and it `lerp`s its offset and blurRadius without changing its color. Visually it looks fine to me.

2025-01-22 21:24 UTC, chrisbobbe commented on lib/widgets/compose_box.dart
> +      boxShadow: BoxShadow.lerpList(boxShadow, other.boxShadow, t)!,
Oh, and it would be good to have a test for this lerping logic, basically just to make sure it doesn't have an unexpected error. It doesn't have to be long, like:

```dart
      testWidgets('lerp light to dark, no crash', (tester) async {
        final a = ComposeBoxTheme.light;
        final b = ComposeBoxTheme.dark;
        check(() => a.lerp(b, 0.5)).returnsNormally();
      });
```

2025-01-27 15:29 UTC, lakshya1goel commented
Thank you for the reviews @PIG208 and @chrisbobbe , I have made the required changes. Please let me know if anything else is required.

2025-01-27 18:52 UTC, PIG208 commented on test/widgets/compose_box_test.dart
> +  testWidgets('lerp light to dark, no crash', (tester) async {
nit: tester is unused; this can use `test` instead

2025-01-27 18:53 UTC, PIG208 commented
LGTM with one nit! Adding the integration tag but leaving the maintainer review in case Chris has anything to add.

2025-01-28 06:08 UTC, lakshya1goel commented
Thanks for the review @PIG208, pushed the revision.

2025-01-28 18:32 UTC, PIG208 commented on test/widgets/compose_box_test.dart
> +  testWidgets('lerp light to dark, no crash', (tester) async {
Just saw your update! I meant instead of using `testWidgets`, we should use `test` the function, not renaming the parameter to `test`.

2025-01-28 19:14 UTC, lakshya1goel commented on test/widgets/compose_box_test.dart
> +  testWidgets('lerp light to dark, no crash', (tester) async {
Ohh, sorry for misinterpreting. Thanks for pointing out again. Pushed the revision.

2025-01-28 20:15 UTC, chrisbobbe reviewed
Thanks! Very small comments below.

2025-01-28 20:15 UTC, chrisbobbe commented on lib/widgets/compose_box.dart
> +/// Compose-box styles that differ between light and dark theme.
```
compose: Make compose-box border more prominent in dark mode

Updated the top border and added shadow effect to the top of
the compose box to ensure it is subtle in dark mode.

For reference, see the Figma design:
https://www.figma.com/design/1JTNtYo9memgW7vV6d0ygq/Zulip-Mobile?node-id=5908-64038&t=alSmAmdRXFDwT4IT-1

Fixes: #1207
```

Commit-message nit: "[…] to ensure it is subtle in dark mode" isn't right 🙂—"subtle" would mean the visual distinction is _less_ obvious, and the point is to make it more obvious.

Instead, how about "to make it more visible in dark mode", or something like that?

2025-01-28 20:15 UTC, chrisbobbe commented on test/widgets/compose_box_test.dart
> +
Let's wrap this in a `group('ComposeBoxTheme'` and put it near the other `group`s.

2025-01-28 20:36 UTC, lakshya1goel commented on lib/widgets/compose_box.dart
> +/// Compose-box styles that differ between light and dark theme.
Ahh, sorry missed it last time.

2025-01-31 21:24 UTC, gnprice reviewed
Thanks @lakshya1goel for taking care of this, and @chrisbobbe and @PIG208 for the previous reviews!

These changes all look good. Just a couple of comments — one on the commit message, below, and two on the PR text:

The PR description is backward from what the PR does:
> to ensure it is subtle in dark mode.

I think this is the same issue as https://github.com/zulip/zulip-flutter/pull/1233#discussion_r1932799377 .

The PR title says:
> compose: Compose-box border is subtle in dark mode

which matches the issue title. But a PR title should say what the PR does, not describe the status quo from before the PR.

A good solution for both would be to edit the PR title and description to match the commit message. In general a PR title and description do a very similar job to a commit message; so when a PR has just one commit, they should usually be very similar to that one commit's message.

2025-01-31 21:24 UTC, gnprice commented on lib/widgets/compose_box.dart
> +        boxShadow: ComposeBoxTheme.of(context).boxShadow,
The commit message says:

    For reference, see the Figma design:
    https://www.figma.com/design/1JTNtYo9memgW7vV6d0ygq/Zulip-Mobile\?node-id\=5908-64038\&t\=alSmAmdRXFDwT4IT-1

That link doesn't work, though. I think the `\` characters are undesired.

2025-02-01 06:51 UTC, lakshya1goel commented on lib/widgets/compose_box.dart
> +        boxShadow: ComposeBoxTheme.of(context).boxShadow,
Ohh, thanks for pointing. Corrected it.

2025-02-01 06:54 UTC, lakshya1goel commented
Thanks for the review @gnprice, updated the PR accordingly, PTAL.

2025-02-04 22:17 UTC, merged

2025-02-04 22:17 UTC, gnprice commented
Thanks! Looks good; merging.