added connecting snackbar and snackbar.dart file
zulip/zulip-flutter pull request #584
Opened 2024-03-24 09:50 UTC by satyam372

Added 'snackbar.dart' file to show the snackbar. I have created this file inside widget folder and then imported it in app.dart and message_list.dart file . 

working : I have used "connectivity_plus: ^5.0.2" package to implement this.   This package allows developers to see the connectivity of device . This helps us to determine  whether our device has active internet connection or not .

Video link:-
https://github.com/zulip/zulip-flutter/assets/112092492/911a49a4-568c-4b29-82bc-1c8d0bf5872b

2024-03-24 15:13 UTC, Khader-1 commented on lib/widgets/app.dart
> +        child: Builder(builder: (context) {
Update your code editors spacing to match the repo configuration. check the [ReadMe File](https://github.com/zulip/zulip-flutter?tab=readme-ov-file#code-formatting)

2024-03-24 15:33 UTC, Khader-1 commented on pubspec.yaml
> +  sdk: '>=3.4.0-140.0.dev <4.0.0'
Never change the sdk version in pubspec.yaml as it is configured for the whole team. refer to [ReadMe](https://github.com/zulip/zulip-flutter?tab=readme-ov-file#flutter-version)

2024-03-24 15:41 UTC, Khader-1 commented on pubspec.yaml
> +  fluttertoast: ^8.2.4
As mentioned by @gnprice in [the stream](https://chat.zulip.org/#narrow/stream/48-mobile/topic/.23F465.20Show.20.22Connecting.E2.80.A6.22.20banner.20.28or.20equivalent.29.20when.20serv.2E.2E.2E/near/1763901) no need to use `fluttertoast`

2024-03-24 15:43 UTC, Khader-1 requested changes
You're doing good but you need to refer to the contribution guides linked in the comments.

2024-03-24 15:45 UTC, Khader-1 commented
Nice work but it can be improved, according to the [commits discipline](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.html) your commits need some restructure.

2024-03-24 17:56 UTC, closed without merging

2024-03-24 18:56 UTC, satyam372 commented
thankyou @Khader-1 for your feedback . appreciated your inputs and i will definetly work on it

2024-03-25 07:37 UTC, gnprice commented
Thanks @Khader-1 for the initial review! And thanks @satyam372 for the contribution.

For cross-reference: it looks like this started as #583 and then became #586.

@satyam372 For future pull requests, it's better to update the existing PR than to close it and open a new one. See https://zulip.readthedocs.io/en/latest/git/pull-requests.html#update-a-pull-request .